### ISSUE TITLE
All properties are optional in type from schema

### ISSUE THREAD

**Issue by stpoa** [neuledge/computed-types#200] opened 2022-10-21 15:16 UTC
All properties in type from schema are optional. Example below.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/19593179/197229922-addc21c2-229d-4f0a-bd99-c16f2b80e000.png">

Readme shows that only the `flags` property should be optional.

TS: 4.6.3

**Comment by moshest** [comment] 2022-10-22 20:50
Can you provide full project setup? I can't reproduce it and all tests passes:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/534911/197361841-ac16061b-1c6b-4e6d-85a7-65c3660335b5.png">

**Comment by stpoa** [comment] 2022-10-24 15:24
https://codesandbox.io/s/cool-visvesvaraya-dpubbe?file=/src/index.ts

**Comment by moshest** [comment] 2022-10-25 05:31
This probably an issue with [codesandbox.io](https://codesandbox.io).

I still can't reproduce it, I created an empty project via VS Code and got the following:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/534911/197690149-f429216c-6854-4a9e-bd10-9727144e0204.png">

I used the following commands:
```bash
mkdir test & cd test
yarn init
yarn add -D typescript
yarn tsc --init
yarn add computed-types
```

Closing this until I see proper reproduction instructions.

**Closed by moshest** 2022-10-25 05:31 UTC
Labels: invalid, awaiting feedback

**Comment by stpoa** [comment] 2022-10-25 08:06
Had the same problem locally. So not only with codesandbox.

**Comment by stpoa** [comment] 2022-10-25 08:10
I downloaded the codesandbox code and installed dependencies with yarn and locally I have the same problem.

![image](https://user-images.githubusercontent.com/19593179/197719487-3314c789-5c0a-4324-afeb-e4db9c974595.png)

**Comment by moshest** [comment] 2022-10-25 14:21
Hi @stpoa, I just notice I missed you comment about the custom TypeScript settings and manage to reproduce it with it:

```
 "strictNullChecks": false
```

Apologies for the miss understanding. I've update the issue description to make it more clear.

TypeScript behave very differently on that state. It will ignore `null` and `undefined` values, and always assume values will exists even if that's definitely not the case:
```ts
const obj: { foo?: { bar: number } } = {};
console.log(obj.foo.bar); // <- will throw!
```

Unfortunately I don't feel it's a priority, but I'm open to merge a PR if we make sure all tests passes on strict mode as well.
